-- shader_gen.lua
local reg = require("registry")

local function generate_ssot(glsl_path, c_header_path)
    -- 1. Generate GLSL Constants
    local glsl = io.open(glsl_path, "w")
    glsl:write("// AUTO-GENERATED FROM registry.lua\n")
    glsl:write("#ifndef REGISTRY_GLSL\n#define REGISTRY_GLSL\n\n")

    glsl:write("// --- RENDER MODES ---\n")
    for key, val in pairs(reg.mode) do
        glsl:write(string.format("const uint MODE_%s = %dU;\n", string.upper(key), val))
    end
    glsl:write("\n// --- ENGINE CONSTANTS ---\n")
    for key, val in pairs(reg.cfg) do
        glsl:write(string.format("const uint CFG_%s = %dU;\n", string.upper(key), val))
    end

    glsl:write("\n#endif // REGISTRY_GLSL\n")
    glsl:close()
    print("[LUA SSOT] Wrote " .. glsl_path)

    -- 2. Generate C Shared Structs Header
    local c_hdr = io.open(c_header_path, "w")
    c_hdr:write("// ==========================================\n")
    c_hdr:write("// AUTO-GENERATED FROM registry.lua\n")
    c_hdr:write("// DO NOT EDIT THIS FILE DIRECTLY!\n")
    c_hdr:write("// ==========================================\n\n")
    c_hdr:write("#pragma once\n#include <stdint.h>\n\n")

    -- Write the universal math and command structures
    c_hdr:write(reg.c_math_structs)

    -- Inject the C macro to protect vx_math.c from Vulkan types!
    c_hdr:write("\n\n#ifdef VX_ENABLE_VULKAN_STRUCTS\n")
    c_hdr:write(reg.c_vk_structs)
    c_hdr:write("\n#endif // VX_ENABLE_VULKAN_STRUCTS\n")

    c_hdr:close()
    print("[LUA SSOT] Wrote " .. c_header_path)
end

return { generate = generate_ssot }
