-- shader_gen.lua
local reg = require("registry")

local function generate_glsl_registry(filepath)
    local file = io.open(filepath, "w")
    if not file then error("Could not open " .. filepath .. " for writing") end

    file:write("// ==========================================\n")
    file:write("// AUTO-GENERATED FROM registry.lua\n")
    file:write("// DO NOT EDIT THIS FILE DIRECTLY!\n")
    file:write("// ==========================================\n\n")
    file:write("#ifndef REGISTRY_GLSL\n")
    file:write("#define REGISTRY_GLSL\n\n")

    file:write("// --- RENDER MODES ---\n")
    for key, val in pairs(reg.mode) do
        file:write(string.format("const uint MODE_%s = %dU;\n", string.upper(key), val))
    end
    file:write("\n")

    file:write("// --- ENGINE CONSTANTS ---\n")
    for key, val in pairs(reg.cfg) do
        file:write(string.format("const uint CFG_%s = %dU;\n", string.upper(key), val))
    end
    file:write("\n")

    file:write("#endif // REGISTRY_GLSL\n")
    file:close()

    print("[LUA SHADER GEN] Successfully wrote " .. filepath)
end

return { generate = generate_glsl_registry }
